# Generated by Django 5.1.2 on 2025-09-21 09:22

import ocr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayPayDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypay_image', models.ImageField(blank=True, help_text='PayPayのQRコード画像をアップロードしてください', null=True, upload_to=ocr.models.paypay_image_path, verbose_name='PayPayコード画像')),
                ('message', models.TextField(default='このサービスの維持・改善にご協力ください', help_text='寄付をお願いする際に表示するメッセージ', verbose_name='寄付メッセージ')),
                ('is_active', models.BooleanField(default=True, help_text='現在使用中の寄付コードかどうか', verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('expires_at', models.DateTimeField(help_text='PayPayコードの有効期限', verbose_name='有効期限')),
            ],
            options={
                'verbose_name': 'PayPay寄付設定',
                'verbose_name_plural': 'PayPay寄付設定',
                'ordering': ['-created_at'],
            },
        ),
    ]
